Repository AY2425S1-CS2103T-F15-2/tp, pull requests merged in 2024-10, with the labels that each got.

#12 Add Julian's Photo
  docs/images/IMG_5771.png
  docs/images/juliantayyc.png
Labels: type.Enhancement, priority.Low

#15 Add Brandon's Photo
  docs/images/btbrandon.png
Labels: type.Enhancement, priority.Low

#11 Add Ethan's Photo
  docs/images/ethan-goh.png
Labels: type.Enhancement, priority.Low

#25 Add Julian's About Us
  docs/AboutUs.md
Labels: type.Enhancement, priority.Low

#24 Add Brandon's AboutUs
  docs/AboutUs.md
  docs/team/btbrandon.md
Labels: type.Enhancement, priority.Low

#26 Add Jessica's About Us
  docs/AboutUs.md
  docs/team/jessica2828.md
Labels: type.Enhancement, priority.Low

#33 Update readme
  README.md
  docs/_markbind/layouts/default.md
  docs/images/IMG_5771.png
  docs/site.json
  docs/team/juliantayyc.md
Labels: type.Task, priority.Medium

#35 Update DG: User Profile
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#34 Update DG: NFR and Glossary
  README.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#37 UI Mockup
  docs/images/Ui.png
Labels: type.Task, priority.Medium

#43 Add New Fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/ModuleTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentIdTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#45 Refactor Tag Field and Update AddCommand
  docs/img.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/person/exceptions/InvalidStudentIdException.java
  src/main/java/seedu/address/model/person/exceptions/InvalidTagException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TagTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#46 Fix DG Bugs
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High

#48 Update Ui component
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.High

#47 Update Delete Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.High

#55 Refactor Edit Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Enhancement, priority.High

#58 Minor bug fix to EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Enhancement, priority.High

#64 Add module storage
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#63 Refactor Help Page
  build.gradle
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.High

#65 Update User Guide URL
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#78 Add Command History functionality
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/util/CommandHistory.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: priority.High

#81 Remove id prefix & add Delete by Module
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/ModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeCommandParser.java
  src/main/java/seedu/address/logic/parser/ModuleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#79 Update HelpWindow
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#99 Refactor DeleteSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.High

#100 Refactor ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#101 Refactor HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#104 Refactor ArchitectureSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: priority.Medium

#107 Edit BetterModelCLassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: priority.Medium

#102 Update Case Insensitivity
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ModuleCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#103 Refactor DG Model Component, Planned Enhancements
  docs/DeveloperGuide.md
Labels: priority.Medium

#121 Update DG Storage Component
  docs/DeveloperGuide.md
Labels: priority.High
