Repository AY2425S1-CS2103T-F15-2/tp, pull requests merged in 2024-11, with the labels that each got.

#125 Add CommandHistory to DG
  docs/DeveloperGuide.md
Labels: priority.High

#124 Add module command to UG
  docs/UserGuide.md
  docs/images/addModule.png
Labels: priority.High

#120 Update UG, Fix Bugs
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addCommandResult.png
  docs/images/alternativeHelp.png
  docs/images/deleteCommandResult.png
  docs/images/editCommandResult.png
  docs/images/listCommandResult.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: alpha-bug

#118 Update TagTest, EditCommandTest
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/TagTest.java
Labels: priority.High

#126 Update Grade Command in UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: priority.High

#128 Fix UI issue on Windows OS
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.High, severity.High, alpha-bug

#156 Fix UG formatting in PDF
  docs/UserGuide.md
  docs/site.json
Labels: priority.High, alpha-bug

#132 Fix HelpWindow and FilterCommand bugs
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, alpha-bug

#153 Fix bugs related to Find Command and Delete Command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Low, alpha-bug

#146 Fix bug where phone number doesn't adhere to agreed-upon format
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableEduContactsTest/typicalPersonsEduContacts.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, alpha-bug

#152 Fix Alpha Bugs
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/ModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeCommandTest.java
  src/test/java/seedu/address/logic/commands/ModuleCommandTest.java
Labels: priority.High, alpha-bug

#123 Update FilterCommand Tests
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ModuleContainsKeywordsPredicateTest.java
Labels: priority.Medium

#154 Change Tag class to Role
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/person/exceptions/InvalidRoleException.java
  src/main/java/seedu/address/model/person/exceptions/InvalidTagException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonDetails.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableEduContactsTest/duplicatePersonEduContacts.json
  src/test/data/JsonSerializableEduContactsTest/invalidPersonEduContacts.json
  src/test/data/JsonSerializableEduContactsTest/typicalPersonsEduContacts.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/EduContactsTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/model/person/TagTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#160 Fix Alpha Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: alpha-bug

#122 Update DeleteCommand tests
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium

#163 Fix HelpWindow, helpMessage.png bugs
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, alpha-bug

#171 Change release version in MainApp.java
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#174 Fix UG Bugs
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/deleteModuleResult.png
  docs/images/helpMessage.png
Labels: type.Bug, priority.High, alpha-bug

#252 Fix PE-D UG Bugs
  docs/UserGuide.md
Labels: priority.High, type.DocumentationBug, type.UG

#259 Duplicate role undetected
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: severity.Low, type.FunctionalityBug

#262 Fix FilterCommand bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/ModuleContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/ModuleContainsKeywordsPredicateTest.java
Labels: type.FunctionalityBug

#254 Fix ModuleCommand Bug
  src/main/java/seedu/address/model/person/Module.java
Labels: severity.Low, type.FunctionalityBug

#255 Fix Functionality bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/ModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Module.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: severity.Medium, type.DocumentationBug, type.FunctionalityBug, type.UG

#266 Add help menu known issue to UG
  docs/UserGuide.md
Labels: type.DocumentationBug, type.UG

#265 Update dg
  docs/DeveloperGuide.md
Labels: type.DocumentationBug, type.DG

#271 Update planned enhancements to follow requirement
  docs/DeveloperGuide.md
Labels: type.PlannedEnhancement, type.DocumentationBug, type.DG

#272 Update table of contents
  docs/DeveloperGuide.md
Labels: severity.VeryLow, type.DocumentationBug, type.DG
